stages:
  - build
  - deploy

build:
  stage: build
  image: jojomi/hugo:0.83
  script:
    - hugo version
    - git submodule update --init --recursive
    - hugo -d public_html --config config.toml,home.toml --cleanDestinationDir
  artifacts:
    paths:
      - public_html
  only:
    - master
    - staging

deploy:
  stage: deploy
  image: dinofizz/rsync-ssh
  script:
    - echo "${SSH_PRIVATE_KEY}" > ssh_key
    - chmod 700 ssh_key
    - mkdir "${HOME}/.ssh"
    - echo "${SSH_HOST_KEY}" > "${HOME}/.ssh/known_hosts"
    - rsync -hrvz --delete --exclude=_ -e 'ssh -vi ssh_key -o "StrictHostKeychecking no"' public_html/ "${SSH_USER_HOST_LOCATION}"
  only:
    - master

deploy_staging:
  stage: deploy
  image: dinofizz/rsync-ssh
  script:
    - echo "${SSH_PRIVATE_KEY_STAGING}" > ssh_key
    - chmod 700 ssh_key
    - mkdir "${HOME}/.ssh"
    - echo "${SSH_HOST_KEY}" > "${HOME}/.ssh/known_hosts"
    - rsync -hrvz --delete --exclude=_ -e 'ssh -vi ssh_key -o "StrictHostKeychecking no"' public_html/ "${SSH_USER_HOST_LOCATION_STAGING}"
  only:
    - staging
